runserver:
	../.venv/bin/python manage.py runserver

migrations:
	../.venv/bin/python manage.py makemigrations
	../.venv/bin/python manage.py migrate

tailwind-compile:
	npx @tailwindcss/cli -i ./src/input.css -o ./mysite/static/css/output.css