# Generated by Django 6.1 on 2026-09-02 13:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.RichTextField(null=True),
        ),
    ]
